---@class CreatableInstances
---@field Folder Folder
---@field BasePart BasePart
---@field RenderGroup RenderGroup
---@field GlobalLight GlobalLight
---@field PointLight PointLight
---@field Spotlight Spotlight
---@field AreaLight AreaLight
---@field Frame Frame
---@field TextLabel TextLabel
---@field ImageLabel ImageLabel
---@field SurfaceGui SurfaceGui
---@field BillboardGui BillboardGui
